package kafka

type ErrorCode int16

const (
	UNKNOWN_SERVER_ERROR                  ErrorCode = -1
	NONE                                  ErrorCode = 0
	OFFSET_OUT_OF_RANGE                   ErrorCode = 1
	CORRUPT_MESSAGE                       ErrorCode = 2
	UNKNOWN_TOPIC_OR_PARTITION            ErrorCode = 3
	INVALID_FETCH_SIZE                    ErrorCode = 4
	LEADER_NOT_AVAILABLE                  ErrorCode = 5
	NOT_LEADER_OR_FOLLOWER                ErrorCode = 6
	REQUEST_TIMED_OUT                     ErrorCode = 7
	BROKER_NOT_AVAILABLE                  ErrorCode = 8
	REPLICA_NOT_AVAILABLE                 ErrorCode = 9
	MESSAGE_TOO_LARGE                     ErrorCode = 10
	STALE_CONTROLLER_EPOCH                ErrorCode = 11
	OFFSET_METADATA_TOO_LARGE             ErrorCode = 12
	NETWORK_EXCEPTION                     ErrorCode = 13
	COORDINATOR_LOAD_IN_PROGRESS          ErrorCode = 14
	COORDINATOR_NOT_AVAILABLE             ErrorCode = 15
	NOT_COORDINATOR                       ErrorCode = 16
	INVALID_TOPIC_EXCEPTION               ErrorCode = 17
	RECORD_LIST_TOO_LARGE                 ErrorCode = 18
	NOT_ENOUGH_REPLICAS                   ErrorCode = 19
	NOT_ENOUGH_REPLICAS_AFTER_APPEND      ErrorCode = 20
	INVALID_REQUIRED_ACKS                 ErrorCode = 21
	ILLEGAL_GENERATION                    ErrorCode = 22
	INCONSISTENT_GROUP_PROTOCOL           ErrorCode = 23
	INVALID_GROUP_ID                      ErrorCode = 24
	UNKNOWN_MEMBER_ID                     ErrorCode = 25
	INVALID_SESSION_TIMEOUT               ErrorCode = 26
	REBALANCE_IN_PROGRESS                 ErrorCode = 27
	INVALID_COMMIT_OFFSET_SIZE            ErrorCode = 28
	TOPIC_AUTHORIZATION_FAILED            ErrorCode = 29
	GROUP_AUTHORIZATION_FAILED            ErrorCode = 30
	CLUSTER_AUTHORIZATION_FAILED          ErrorCode = 31
	INVALID_TIMESTAMP                     ErrorCode = 32
	UNSUPPORTED_SASL_MECHANISM            ErrorCode = 33
	ILLEGAL_SASL_STATE                    ErrorCode = 34
	UNSUPPORTED_VERSION                   ErrorCode = 35
	TOPIC_ALREADY_EXISTS                  ErrorCode = 36
	INVALID_PARTITIONS                    ErrorCode = 37
	INVALID_REPLICATION_FACTOR            ErrorCode = 38
	INVALID_REPLICA_ASSIGNMENT            ErrorCode = 39
	INVALID_CONFIG                        ErrorCode = 40
	NOT_CONTROLLER                        ErrorCode = 41
	INVALID_REQUEST                       ErrorCode = 42
	UNSUPPORTED_FOR_MESSAGE_FORMAT        ErrorCode = 43
	POLICY_VIOLATION                      ErrorCode = 44
	OUT_OF_ORDER_SEQUENCE_NUMBER          ErrorCode = 45
	DUPLICATE_SEQUENCE_NUMBER             ErrorCode = 46
	INVALID_PRODUCER_EPOCH                ErrorCode = 47
	INVALID_TXN_STATE                     ErrorCode = 48
	INVALID_PRODUCER_ID_MAPPING           ErrorCode = 49
	INVALID_TRANSACTION_TIMEOUT           ErrorCode = 50
	CONCURRENT_TRANSACTIONS               ErrorCode = 51
	TRANSACTION_COORDINATOR_FENCED        ErrorCode = 52
	TRANSACTIONAL_ID_AUTHORIZATION_FAILED ErrorCode = 53
	SECURITY_DISABLED                     ErrorCode = 54
	OPERATION_NOT_ATTEMPTED               ErrorCode = 55
	KAFKA_STORAGE_ERROR                   ErrorCode = 56
	LOG_DIR_NOT_FOUND                     ErrorCode = 57
	SASL_AUTHENTICATION_FAILED            ErrorCode = 58
	UNKNOWN_PRODUCER_ID                   ErrorCode = 59
	REASSIGNMENT_IN_PROGRESS              ErrorCode = 60
	DELEGATION_TOKEN_AUTH_DISABLED        ErrorCode = 61
	DELEGATION_TOKEN_NOT_FOUND            ErrorCode = 62
	DELEGATION_TOKEN_OWNER_MISMATCH       ErrorCode = 63
	DELEGATION_TOKEN_REQUEST_NOT_ALLOWED  ErrorCode = 64
	DELEGATION_TOKEN_AUTHORIZATION_FAILED ErrorCode = 65
	DELEGATION_TOKEN_EXPIRED              ErrorCode = 66
	INVALID_PRINCIPAL_TYPE                ErrorCode = 67
	NON_EMPTY_GROUP                       ErrorCode = 68
	GROUP_ID_NOT_FOUND                    ErrorCode = 69
	FETCH_SESSION_ID_NOT_FOUND            ErrorCode = 70
	INVALID_FETCH_SESSION_EPOCH           ErrorCode = 71
	LISTENER_NOT_FOUND                    ErrorCode = 72
	TOPIC_DELETION_DISABLED               ErrorCode = 73
	FENCED_LEADER_EPOCH                   ErrorCode = 74
	UNKNOWN_LEADER_EPOCH                  ErrorCode = 75
	UNSUPPORTED_COMPRESSION_TYPE          ErrorCode = 76
	STALE_BROKER_EPOCH                    ErrorCode = 77
	OFFSET_NOT_AVAILABLE                  ErrorCode = 78
	MEMBER_ID_REQUIRED                    ErrorCode = 79
	PREFERRED_LEADER_NOT_AVAILABLE        ErrorCode = 80
	GROUP_MAX_SIZE_REACHED                ErrorCode = 81
	FENCED_INSTANCE_ID                    ErrorCode = 82
	ELIGIBLE_LEADERS_NOT_AVAILABLE        ErrorCode = 83
	ELECTION_NOT_NEEDED                   ErrorCode = 84
	NO_REASSIGNMENT_IN_PROGRESS           ErrorCode = 85
	GROUP_SUBSCRIBED_TO_TOPIC             ErrorCode = 86
	INVALID_RECORD                        ErrorCode = 87
	UNSTABLE_OFFSET_COMMIT                ErrorCode = 88
	THROTTLING_QUOTA_EXCEEDED             ErrorCode = 89
	PRODUCER_FENCED                       ErrorCode = 90
	RESOURCE_NOT_FOUND                    ErrorCode = 91
	DUPLICATE_RESOURCE                    ErrorCode = 92
	UNACCEPTABLE_CREDENTIAL               ErrorCode = 93
	INCONSISTENT_VOTER_SET                ErrorCode = 94
	INVALID_UPDATE_VERSION                ErrorCode = 95
	FEATURE_UPDATE_FAILED                 ErrorCode = 96
	PRINCIPAL_DESERIALIZATION_FAILURE     ErrorCode = 97
	SNAPSHOT_NOT_FOUND                    ErrorCode = 98
	POSITION_OUT_OF_RANGE                 ErrorCode = 99
	UNKNOWN_TOPIC_ID                      ErrorCode = 100
	DUPLICATE_BROKER_REGISTRATION         ErrorCode = 101
	BROKER_ID_NOT_REGISTERED              ErrorCode = 102
	INCONSISTENT_TOPIC_ID                 ErrorCode = 103
	INCONSISTENT_CLUSTER_ID               ErrorCode = 104
	TRANSACTIONAL_ID_NOT_FOUND            ErrorCode = 105
	FETCH_SESSION_TOPIC_ID_ERROR          ErrorCode = 106
	INELIGIBLE_REPLICA                    ErrorCode = 107
	NEW_LEADER_ELECTED                    ErrorCode = 108
)

var errorCodeStrings = [...]string{
	NONE:                                  "NONE",
	OFFSET_OUT_OF_RANGE:                   "OFFSET_OUT_OF_RANGE",
	CORRUPT_MESSAGE:                       "CORRUPT_MESSAGE",
	UNKNOWN_TOPIC_OR_PARTITION:            "UNKNOWN_TOPIC_OR_PARTITION",
	INVALID_FETCH_SIZE:                    "INVALID_FETCH_SIZE",
	LEADER_NOT_AVAILABLE:                  "LEADER_NOT_AVAILABLE",
	NOT_LEADER_OR_FOLLOWER:                "NOT_LEADER_OR_FOLLOWER",
	REQUEST_TIMED_OUT:                     "REQUEST_TIMED_OUT",
	BROKER_NOT_AVAILABLE:                  "BROKER_NOT_AVAILABLE",
	REPLICA_NOT_AVAILABLE:                 "REPLICA_NOT_AVAILABLE",
	MESSAGE_TOO_LARGE:                     "MESSAGE_TOO_LARGE",
	STALE_CONTROLLER_EPOCH:                "STALE_CONTROLLER_EPOCH",
	OFFSET_METADATA_TOO_LARGE:             "OFFSET_METADATA_TOO_LARGE",
	NETWORK_EXCEPTION:                     "NETWORK_EXCEPTION",
	COORDINATOR_LOAD_IN_PROGRESS:          "COORDINATOR_LOAD_IN_PROGRESS",
	COORDINATOR_NOT_AVAILABLE:             "COORDINATOR_NOT_AVAILABLE",
	NOT_COORDINATOR:                       "NOT_COORDINATOR",
	INVALID_TOPIC_EXCEPTION:               "INVALID_TOPIC_EXCEPTION",
	RECORD_LIST_TOO_LARGE:                 "RECORD_LIST_TOO_LARGE",
	NOT_ENOUGH_REPLICAS:                   "NOT_ENOUGH_REPLICAS",
	NOT_ENOUGH_REPLICAS_AFTER_APPEND:      "NOT_ENOUGH_REPLICAS_AFTER_APPEND",
	INVALID_REQUIRED_ACKS:                 "INVALID_REQUIRED_ACKS",
	ILLEGAL_GENERATION:                    "ILLEGAL_GENERATION",
	INCONSISTENT_GROUP_PROTOCOL:           "INCONSISTENT_GROUP_PROTOCOL",
	INVALID_GROUP_ID:                      "INVALID_GROUP_ID",
	UNKNOWN_MEMBER_ID:                     "UNKNOWN_MEMBER_ID",
	INVALID_SESSION_TIMEOUT:               "INVALID_SESSION_TIMEOUT",
	REBALANCE_IN_PROGRESS:                 "REBALANCE_IN_PROGRESS",
	INVALID_COMMIT_OFFSET_SIZE:            "INVALID_COMMIT_OFFSET_SIZE",
	TOPIC_AUTHORIZATION_FAILED:            "TOPIC_AUTHORIZATION_FAILED",
	GROUP_AUTHORIZATION_FAILED:            "GROUP_AUTHORIZATION_FAILED",
	CLUSTER_AUTHORIZATION_FAILED:          "CLUSTER_AUTHORIZATION_FAILED",
	INVALID_TIMESTAMP:                     "INVALID_TIMESTAMP",
	UNSUPPORTED_SASL_MECHANISM:            "UNSUPPORTED_SASL_MECHANISM",
	ILLEGAL_SASL_STATE:                    "ILLEGAL_SASL_STATE",
	UNSUPPORTED_VERSION:                   "UNSUPPORTED_VERSION",
	TOPIC_ALREADY_EXISTS:                  "TOPIC_ALREADY_EXISTS",
	INVALID_PARTITIONS:                    "INVALID_PARTITIONS",
	INVALID_REPLICATION_FACTOR:            "INVALID_REPLICATION_FACTOR",
	INVALID_REPLICA_ASSIGNMENT:            "INVALID_REPLICA_ASSIGNMENT",
	INVALID_CONFIG:                        "INVALID_CONFIG",
	NOT_CONTROLLER:                        "NOT_CONTROLLER",
	INVALID_REQUEST:                       "INVALID_REQUEST",
	UNSUPPORTED_FOR_MESSAGE_FORMAT:        "UNSUPPORTED_FOR_MESSAGE_FORMAT",
	POLICY_VIOLATION:                      "POLICY_VIOLATION",
	OUT_OF_ORDER_SEQUENCE_NUMBER:          "OUT_OF_ORDER_SEQUENCE_NUMBER",
	DUPLICATE_SEQUENCE_NUMBER:             "DUPLICATE_SEQUENCE_NUMBER",
	INVALID_PRODUCER_EPOCH:                "INVALID_PRODUCER_EPOCH",
	INVALID_TXN_STATE:                     "INVALID_TXN_STATE",
	INVALID_PRODUCER_ID_MAPPING:           "INVALID_PRODUCER_ID_MAPPING",
	INVALID_TRANSACTION_TIMEOUT:           "INVALID_TRANSACTION_TIMEOUT",
	CONCURRENT_TRANSACTIONS:               "CONCURRENT_TRANSACTIONS",
	TRANSACTION_COORDINATOR_FENCED:        "TRANSACTION_COORDINATOR_FENCED",
	TRANSACTIONAL_ID_AUTHORIZATION_FAILED: "TRANSACTIONAL_ID_AUTHORIZATION_FAILED",
	SECURITY_DISABLED:                     "SECURITY_DISABLED",
	OPERATION_NOT_ATTEMPTED:               "OPERATION_NOT_ATTEMPTED",
	KAFKA_STORAGE_ERROR:                   "KAFKA_STORAGE_ERROR",
	LOG_DIR_NOT_FOUND:                     "LOG_DIR_NOT_FOUND",
	SASL_AUTHENTICATION_FAILED:            "SASL_AUTHENTICATION_FAILED",
	UNKNOWN_PRODUCER_ID:                   "UNKNOWN_PRODUCER_ID",
	REASSIGNMENT_IN_PROGRESS:              "REASSIGNMENT_IN_PROGRESS",
	DELEGATION_TOKEN_AUTH_DISABLED:        "DELEGATION_TOKEN_AUTH_DISABLED",
	DELEGATION_TOKEN_NOT_FOUND:            "DELEGATION_TOKEN_NOT_FOUND",
	DELEGATION_TOKEN_OWNER_MISMATCH:       "DELEGATION_TOKEN_OWNER_MISMATCH",
	DELEGATION_TOKEN_REQUEST_NOT_ALLOWED:  "DELEGATION_TOKEN_REQUEST_NOT_ALLOWED",
	DELEGATION_TOKEN_AUTHORIZATION_FAILED: "DELEGATION_TOKEN_AUTHORIZATION_FAILED",
	DELEGATION_TOKEN_EXPIRED:              "DELEGATION_TOKEN_EXPIRED",
	INVALID_PRINCIPAL_TYPE:                "INVALID_PRINCIPAL_TYPE",
	NON_EMPTY_GROUP:                       "NON_EMPTY_GROUP",
	GROUP_ID_NOT_FOUND:                    "GROUP_ID_NOT_FOUND",
	FETCH_SESSION_ID_NOT_FOUND:            "FETCH_SESSION_ID_NOT_FOUND",
	INVALID_FETCH_SESSION_EPOCH:           "INVALID_FETCH_SESSION_EPOCH",
	LISTENER_NOT_FOUND:                    "LISTENER_NOT_FOUND",
	TOPIC_DELETION_DISABLED:               "TOPIC_DELETION_DISABLED",
	FENCED_LEADER_EPOCH:                   "FENCED_LEADER_EPOCH",
	UNKNOWN_LEADER_EPOCH:                  "UNKNOWN_LEADER_EPOCH",
	UNSUPPORTED_COMPRESSION_TYPE:          "UNSUPPORTED_COMPRESSION_TYPE",
	STALE_BROKER_EPOCH:                    "STALE_BROKER_EPOCH",
	OFFSET_NOT_AVAILABLE:                  "OFFSET_NOT_AVAILABLE",
	MEMBER_ID_REQUIRED:                    "MEMBER_ID_REQUIRED",
	PREFERRED_LEADER_NOT_AVAILABLE:        "PREFERRED_LEADER_NOT_AVAILABLE",
	GROUP_MAX_SIZE_REACHED:                "GROUP_MAX_SIZE_REACHED",
	FENCED_INSTANCE_ID:                    "FENCED_INSTANCE_ID",
	ELIGIBLE_LEADERS_NOT_AVAILABLE:        "ELIGIBLE_LEADERS_NOT_AVAILABLE",
	ELECTION_NOT_NEEDED:                   "ELECTION_NOT_NEEDED",
	NO_REASSIGNMENT_IN_PROGRESS:           "NO_REASSIGNMENT_IN_PROGRESS",
	GROUP_SUBSCRIBED_TO_TOPIC:             "GROUP_SUBSCRIBED_TO_TOPIC",
	INVALID_RECORD:                        "INVALID_RECORD",
	UNSTABLE_OFFSET_COMMIT:                "UNSTABLE_OFFSET_COMMIT",
	THROTTLING_QUOTA_EXCEEDED:             "THROTTLING_QUOTA_EXCEEDED",
	PRODUCER_FENCED:                       "PRODUCER_FENCED",
	RESOURCE_NOT_FOUND:                    "RESOURCE_NOT_FOUND",
	DUPLICATE_RESOURCE:                    "DUPLICATE_RESOURCE",
	UNACCEPTABLE_CREDENTIAL:               "UNACCEPTABLE_CREDENTIAL",
	INCONSISTENT_VOTER_SET:                "INCONSISTENT_VOTER_SET",
	INVALID_UPDATE_VERSION:                "INVALID_UPDATE_VERSION",
	FEATURE_UPDATE_FAILED:                 "FEATURE_UPDATE_FAILED",
	PRINCIPAL_DESERIALIZATION_FAILURE:     "PRINCIPAL_DESERIALIZATION_FAILURE",
	SNAPSHOT_NOT_FOUND:                    "SNAPSHOT_NOT_FOUND",
	POSITION_OUT_OF_RANGE:                 "POSITION_OUT_OF_RANGE",
	UNKNOWN_TOPIC_ID:                      "UNKNOWN_TOPIC_ID",
	DUPLICATE_BROKER_REGISTRATION:         "DUPLICATE_BROKER_REGISTRATION",
	BROKER_ID_NOT_REGISTERED:              "BROKER_ID_NOT_REGISTERED",
	INCONSISTENT_TOPIC_ID:                 "INCONSISTENT_TOPIC_ID",
	INCONSISTENT_CLUSTER_ID:               "INCONSISTENT_CLUSTER_ID",
	TRANSACTIONAL_ID_NOT_FOUND:            "TRANSACTIONAL_ID_NOT_FOUND",
	FETCH_SESSION_TOPIC_ID_ERROR:          "FETCH_SESSION_TOPIC_ID_ERROR",
	INELIGIBLE_REPLICA:                    "INELIGIBLE_REPLICA",
	NEW_LEADER_ELECTED:                    "NEW_LEADER_ELECTED",
}

func (ec ErrorCode) String() string {
	return errorCodeStrings[ec]
}
